// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KriptoBorsaResponse;
//
//    var borsaResponse = BorsaResponse.FromJson(jsonString);

namespace KriptoBorsaResponse
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BorsaResponse
    {
        [JsonProperty("data")]
        public Dictionary<string, string>[] Data { get; set; }

        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }
    }

    public partial class BorsaResponse
    {
        public static BorsaResponse FromJson(string json) => JsonConvert.DeserializeObject<BorsaResponse>(json, KriptoBorsaResponse.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BorsaResponse self) => JsonConvert.SerializeObject(self, KriptoBorsaResponse.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
